package com.shejan.sleepie.ui.theme

object Localization {

    private val english = mapOf(
        "app_name" to "Sleepie",
        "nav_dashboard" to "Dashboard",
        "nav_history" to "History",
        "nav_tips" to "Tips",
        "nav_settings" to "Settings",
        
        // Onboarding
        "onboarding_title" to "Welcome to Sleepie",
        "onboarding_welcome_desc" to "Continuous sleep posture monitoring and snore tracking, completely local and private on your device.",
        "onboarding_privacy" to "🔒 Privacy Promise: All audio analysis and motion data stay on your device. Zero cloud uploads. No internet needed.",
        "onboarding_btn_next" to "Next",
        "onboarding_btn_start" to "Get Started",
        "onboarding_btn_finish" to "Let's Sleep",
        
        "perm_title" to "Required Access",
        "perm_desc" to "To log sleep posture and snore volume through the night, please grant the following permissions:",
        "perm_sensors" to "Motion Sensors",
        "perm_sensors_desc" to "Required to detect posture roll and pitch.",
        "perm_mic" to "Microphone",
        "perm_mic_desc" to "Used local-only to measure snore volume decibels.",
        "perm_notif" to "Notifications",
        "perm_notif_desc" to "Displays active background tracking notifications.",
        "perm_battery" to "Battery Exemption",
        "perm_battery_desc" to "Allow app to run in background without being killed.",
        "perm_granted" to "Granted",
        "perm_grant" to "Grant",
        
        "calib_title" to "Phone Setup",
        "calib_desc" to "For accurate tracking, place the phone flat on the mattress near your pillow. Let's calibrate your device orientation.",
        "calib_btn" to "Start Calibration",
        "calib_back" to "1. Lie flat on your BACK. Hold phone flat.",
        "calib_side" to "2. Lie on your SIDE. Hold phone tilted.",
        "calib_stomach" to "3. Lie on your STOMACH. Hold phone face down.",
        "calib_calibrating" to "Calibrating baseline... Keep still.",
        "calib_done" to "Calibration Complete!",
        
        "profile_title" to "Profile Setup",
        "profile_desc" to "Help us personalize your sleep insights.",
        "profile_age" to "Age",
        "profile_gender" to "Gender",
        "profile_preferred" to "Preferred Position",
        "profile_back" to "Back",
        "profile_side" to "Side",
        "profile_stomach" to "Stomach",
        "profile_conditions" to "Health Conditions (Select all that apply)",
        "cond_back_pain" to "Back Pain",
        "cond_snoring" to "Frequent Snoring",
        "cond_pregnancy" to "Pregnancy",
        "cond_apnea" to "Sleep Apnea History",
        
        "goals_title" to "Sleep Goals",
        "goals_desc" to "What would you like to improve?",
        "goal_reduce_snore" to "Reduce Snoring",
        "goal_back_pain" to "Alleviate Back Pain",
        "goal_sleep_depth" to "Improve Sleep Depth",
        "goal_posture_fix" to "Correct Sleep Posture",
        "alert_sensitivity" to "Alert Vibration Sensitivity",
        "alert_gentle" to "Gentle Haptic",
        "alert_medium" to "Medium Pulse",
        "alert_strong" to "Strong Buzz",
        
        // Dashboard
        "dash_welcome" to "Good Morning,",
        "dash_no_data" to "No sessions logged yet. Sleep well tonight!",
        "dash_score" to "Sleep Score",
        "dash_last_night" to "Last Night Summary",
        "dash_duration" to "Duration",
        "dash_risk" to "Obstruction Risk",
        "dash_start_btn" to "Start Tracking",
        "dash_snore_detected" to "Snoring Detected",
        "dash_snore_not_detected" to "Quiet Night (No Snoring)",
        "dash_expected_score" to "Tonight's Goal",
        "dash_expected_desc" to "Maintain side-sleeping posture to hit your target score.",
        "dash_avg_score" to "Weekly Average",
        
        // Live Screen
        "live_tracking" to "Sleep Tracking Active",
        "live_time" to "Elapsed Time",
        "live_current_posture" to "Current Classified Posture",
        "live_snore_indicator" to "Snore Amplitude Meter",
        "live_status" to "Sensor Status",
        "live_status_ok" to "Green (All Sensors Good)",
        "live_alerts_toggle" to "Haptic Alerts Enable",
        "live_stop_slide" to "Slide/Hold to Stop Session",
        "live_dialog_title" to "Stop Session?",
        "live_dialog_desc" to "Are you sure you want to end tonight's sleep tracking?",
        "live_dialog_yes" to "End Session",
        "live_dialog_no" to "Continue Tracking",
        "live_phase" to "Estimated Sleep Phase",
        "live_phase_light" to "Light Sleep",
        "live_phase_deep" to "Deep Sleep",
        "live_phase_rem" to "REM Sleep",
        "live_phase_awake" to "Awake",
        
        // History
        "hist_title" to "Sleep History",
        "hist_weekly" to "Weekly",
        "hist_monthly" to "Monthly",
        "hist_posture_breakdown" to "Posture Distribution",
        "hist_snore_logs" to "Snoring Incidents",
        "hist_streak" to "Side-Sleeping Streak",
        "hist_streak_desc" to "nights of optimal posture!",
        "hist_sessions_list" to "Past Sessions",
        "hist_detail_title" to "Night Analysis",
        "hist_detail_timeline" to "Posture Timeline",
        "hist_detail_note" to "Morning Reflections Note",
        "hist_detail_note_hint" to "How did you feel waking up? Enter note...",
        "hist_detail_save_note" to "Save Note",
        "hist_detail_alerts" to "Vibration Alerts Triggered",
        "hist_detail_snore_events" to "Snore Episodes",
        "hist_export" to "Export CSV",
        
        // Tips
        "tips_title" to "Insights Hub",
        "tips_top" to "Personalized Advice",
        "tips_edu" to "Sleep Education",
        "tips_badges" to "Achievements",
        "badge_streak_3" to "3-Night Streak",
        "badge_streak_3_desc" to "Logged 3 sleep nights consecutively.",
        "badge_streak_7" to "7-Night Streak",
        "badge_streak_7_desc" to "Logged 7 sleep nights consecutively.",
        "badge_quiet" to "Quiet Sleeper",
        "badge_quiet_desc" to "Slept with under 5% snoring volume.",
        "badge_posture" to "Side Sleeper Champion",
        "badge_posture_desc" to "Slept on side for >75% of the night.",
        
        // Settings
        "settings_title" to "Settings",
        "settings_lang" to "App Language (ভাষা)",
        "settings_redo_calib" to "Redo Sensor Calibration",
        "settings_clear" to "Clear All Data",
        "settings_clear_confirm" to "This will erase all sleep history sessions permanently. Continue?",
        "settings_clear_btn" to "Delete Everything",
        "settings_cancel" to "Cancel"
    )

    private val bengali = mapOf(
        "app_name" to "স্লিপি",
        "nav_dashboard" to "ড্যাশবোর্ড",
        "nav_history" to "ইতিহাস",
        "nav_tips" to "পরামর্শ",
        "nav_settings" to "সেটিংস",
        
        // Onboarding
        "onboarding_title" to "স্লিপিতে আপনাকে স্বাগতম",
        "onboarding_welcome_desc" to "নিরবচ্ছিন্ন ঘুম নিয়ন্ত্রণ এবং নাক ডাকা ট্র্যাকিং, সম্পূর্ণ স্থানীয় এবং আপনার ডিভাইসে সুরক্ষিত থাকবে।",
        "onboarding_privacy" to "🔒 গোপনীয়তার প্রতিশ্রুতি: সকল অডিও বিশ্লেষণ এবং মোশন ডেটা আপনার ফোনে থাকবে। কোনো ক্লাউড আপলোড নেই। কোনো ইন্টারনেট লাগবে না।",
        "onboarding_btn_next" to "পরবর্তী",
        "onboarding_btn_start" to "শুরু করুন",
        "onboarding_btn_finish" to "ঘুমাতে যাই",
        
        "perm_title" to "প্রয়োজনীয় অ্যাক্সেস",
        "perm_desc" to "সারা রাত ঘুমানোর ভঙ্গি এবং নাক ডাকার পরিমাণ রেকর্ড করতে, অনুগ্রহ করে নিম্নলিখিত অনুমতিগুলি দিন:",
        "perm_sensors" to "মোশন সেন্সর",
        "perm_sensors_desc" to "ঘুমের ভঙ্গি নির্ধারণ করতে প্রয়োজন।",
        "perm_mic" to "মাইক্রোফোন",
        "perm_mic_desc" to "নাক ডাকার ভলিউম ডেসিবেল পরিমাপের জন্য ব্যবহুত হয় (সম্পূর্ণ লোকাল)।",
        "perm_notif" to "বিজ্ঞপ্তি",
        "perm_notif_desc" to "চলতি ট্র্যাকিং সম্পর্কিত নোটিফিকেশন প্রদর্শন করবে।",
        "perm_battery" to "ব্যাটারি অপ্টিমাইজেশন নিষ্ক্রিয়",
        "perm_battery_desc" to "অ্যাপটিকে ব্যাকগ্রাউন্ডে বন্ধ হওয়া ছাড়া চলতে দিন।",
        "perm_granted" to "অনুমোদিত",
        "perm_grant" to "অনুমতি দিন",
        
        "calib_title" to "ফোন সেটআপ",
        "calib_desc" to "সঠিক ট্র্যাকিংয়ের জন্য, ফোনটি বালিশের কাছে তোশকের উপর ফ্ল্যাট রাখুন। আসুন আপনার ডিভাইসের ওরিয়েন্টেশন ক্যালিব্রেট করি।",
        "calib_btn" to "ক্যালিব্রেশন শুরু করুন",
        "calib_back" to "১. চিত হয়ে ঘুমান। ফোন ফ্ল্যাট ধরুন।",
        "calib_side" to "২. কাত হয়ে ঘুমান। ফোনটি সামান্য এঙ্গেলে রাখুন।",
        "calib_stomach" to "৩. উপুড় হয়ে ঘুমান। ফোন স্ক্রিন নিচের দিকে রাখুন।",
        "calib_calibrating" to "ক্যালিব্রেট হচ্ছে... নড়াচড়া করবেন না।",
        "calib_done" to "ক্যালিব্রেশন সম্পন্ন হয়েছে!",
        
        "profile_title" to "প্রোফাইল সেটআপ",
        "profile_desc" to "আপনার ঘুমের বিশ্লেষণ ব্যক্তিগতকৃত করতে সাহায্য করুন।",
        "profile_age" to "বয়স",
        "profile_gender" to "লিঙ্গ",
        "profile_preferred" to "পছন্দের ঘুমের ভঙ্গি",
        "profile_back" to "চিত হয়ে",
        "profile_side" to "কাত হয়ে",
        "profile_stomach" to "উপুড় হয়ে",
        "profile_conditions" to "শারীরিক অবস্থা (প্রযোজ্য সব সিলেক্ট করুন)",
        "cond_back_pain" to "কোমর বা পিঠে ব্যথা",
        "cond_snoring" to "ঘন ঘন নাক ডাকা",
        "cond_pregnancy" to "গর্ভাবস্থা",
        "cond_apnea" to "স্লিপ অ্যাপনিয়ার ইতিহাস",
        
        "goals_title" to "ঘুমের লক্ষ্য",
        "goals_desc" to "আপনি কী উন্নতি করতে চান?",
        "goal_reduce_snore" to "নাক ডাকা কমানো",
        "goal_back_pain" to "কোমর ব্যথা উপশম করা",
        "goal_sleep_depth" to "গভীর ঘুম বাড়ানো",
        "goal_posture_fix" to "ঘুমের ভঙ্গি সঠিক করা",
        "alert_sensitivity" to "অ্যালার্ট ভাইব্রেশন সংবেদনশীলতা",
        "alert_gentle" to "মৃদু ভাইব্রেশন",
        "alert_medium" to "মাঝারি ভাইব্রেশন",
        "alert_strong" to "তীব্র ভাইব্রেশন",
        
        // Dashboard
        "dash_welcome" to "শুভ সকাল,",
        "dash_no_data" to "কোনো সেশন রেকর্ড করা নেই। আজ রাতে চমৎকার ঘুমান!",
        "dash_score" to "ঘুমের স্কোর",
        "dash_last_night" to "গত রাতের সারসংক্ষেপ",
        "dash_duration" to "সময়কাল",
        "dash_risk" to "শ্বাসরোধের ঝুঁকি",
        "dash_start_btn" to "ট্র্যাকিং শুরু করুন",
        "dash_snore_detected" to "নাক ডাকা সনাক্ত হয়েছে",
        "dash_snore_not_detected" to "শান্ত রাত (নাক ডাকেনি)",
        "dash_expected_score" to "আজ রাতের লক্ষ্য",
        "dash_expected_desc" to "আপনার লক্ষ্য স্কোরে পৌঁছাতে কাত হয়ে ঘুমানোর অভ্যাস করুন।",
        "dash_avg_score" to "সাপ্তাহিক গড়",
        
        // Live Screen
        "live_tracking" to "স্লিপ ট্র্যাকিং সচল আছে",
        "live_time" to "অতিবাহিত সময়",
        "live_current_posture" to "বর্তমান ঘুমের ভঙ্গি",
        "live_snore_indicator" to "নাক ডাকার শব্দ পরিমাপক",
        "live_status" to "সেন্সরের অবস্থা",
        "live_status_ok" to "সবুজ (সব সেন্সর ঠিক আছে)",
        "live_alerts_toggle" to "ভাইব্রেশন অ্যালার্ট সক্রিয়",
        "live_stop_slide" to "বন্ধ করতে স্লাইড/হোল্ড করুন",
        "live_dialog_title" to "ট্র্যাকিং বন্ধ করবেন?",
        "live_dialog_desc" to "আপনি কি নিশ্চিত যে আজ রাতের স্লিপ ট্র্যাকিং বন্ধ করতে চান?",
        "live_dialog_yes" to "বন্ধ করুন",
        "live_dialog_no" to "চালু রাখুন",
        "live_phase" to "ঘুমের আনুমানিক স্তর",
        "live_phase_light" to "হালকা ঘুম",
        "live_phase_deep" to "গভীর ঘুম",
        "live_phase_rem" to "আরইএম (স্বপ্নীল) ঘুম",
        "live_phase_awake" to "জেগে আছেন",
        
        // History
        "hist_title" to "ঘুমের ইতিহাস",
        "hist_weekly" to "সাপ্তাহিক",
        "hist_monthly" to "মাসিক",
        "hist_posture_breakdown" to "ভঙ্গির বণ্টন",
        "hist_snore_logs" to "নাক ডাকার ঘটনা",
        "hist_streak" to "কাত হয়ে ঘুমানোর ধারাবাহিকতা",
        "hist_streak_desc" to "রাত ধরে আপনি সঠিক ভঙ্গিতে ঘুমাচ্ছেন!",
        "hist_sessions_list" to "অতীতের সেশনসমূহ",
        "hist_detail_title" to "রাতের বিশ্লেষণ",
        "hist_detail_timeline" to "ভঙ্গির টাইমলাইন",
        "hist_detail_note" to "সকালের প্রতিফলন নোট",
        "hist_detail_note_hint" to "ঘুম থেকে ওঠার পর কেমন অনুভব করছেন লিখুন...",
        "hist_detail_save_note" to "নোট সংরক্ষণ করুন",
        "hist_detail_alerts" to "ভাইব্রেশন অ্যালার্টের সংখ্যা",
        "hist_detail_snore_events" to "নাক ডাকার সময়সমূহ",
        "hist_export" to "সিএসভি এক্সপোর্ট",
        
        // Tips
        "tips_title" to "পরামর্শ কেন্দ্র",
        "tips_top" to "ব্যক্তিগতকৃত টিপস",
        "tips_edu" to "ঘুমের শিক্ষা",
        "tips_badges" to "অর্জনসমূহ",
        "badge_streak_3" to "৩ রাতের মেডেল",
        "badge_streak_3_desc" to "টানা ৩ দিন স্লিপ ট্র্যাকিং ব্যবহার করেছেন।",
        "badge_streak_7" to "৭ রাতের মেডেল",
        "badge_streak_7_desc" to "টানা ৭ দিন স্লিপ ট্র্যাকিং ব্যবহার করেছেন।",
        "badge_quiet" to "শান্ত ঘুমন্ত ব্যক্তি",
        "badge_quiet_desc" to "৫%-এর নিচে নাক ডাকার আওয়াজে ঘুমিয়েছেন।",
        "badge_posture" to "কাত হয়ে ঘুমানোর চ্যাম্পিয়ন",
        "badge_posture_desc" to "রাতের ৭৫%-এর বেশি সময় কাত হয়ে ঘুমিয়েছেন।",
        
        // Settings
        "settings_title" to "সেটিংস",
        "settings_lang" to "অ্যাপের ভাষা (Language)",
        "settings_redo_calib" to "সেন্সর পুনরায় ক্যালিব্রেট করুন",
        "settings_clear" to "সব ডাটা মুছে ফেলুন",
        "settings_clear_confirm" to "এটি স্থায়ীভাবে সমস্ত ঘুমের ইতিহাস সেশন মুছে ফেলবে। আপনি কি নিশ্চিত?",
        "settings_clear_btn" to "সবকিছু মুছে ফেলুন",
        "settings_cancel" to "বাতিল"
    )

    fun get(key: String, language: String): String {
        val dictionary = if (language == "bn") bengali else english
        return dictionary[key] ?: english[key] ?: key
    }
}
